### ISSUE TITLE
Install rsync on the local system

### ISSUE THREAD

**Issue by elvgarrui** [linux-system-roles/test-harness#102]
Currently, rsync is not installed by default on the host system. This is necessary in order to correctly copy the integration Python tests from the Network role into every supported distribution. Right now, the needed synchronization is made with a workaround using tar.

Related PR: https://github.com/linux-system-roles/network/pull/260

**Comment by tyll** [comment]
@pcahyna @richm @nhosoi @xjezda00  did you see this? Are there any objections?

**Comment by tyll** [comment]
FYI: anyone who would like to fix this, this needs the container specs (Dockerfiles) to be adjusted to install rsync using yum/dnf and then someone from the system roles core team to deploy the changes.

**Comment by richm** [comment]
No objection from me.  Is there a PR for this?

**Comment by tyll** [comment]
@elvgarrui would you like to take a look? Please note: It is not urgent.

**Comment by liangwen12year** [comment]
I will resolve this issue

**Comment by liangwen12year** [comment]
completed via https://github.com/linux-system-roles/test-harness/pull/112
