### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/test-harness#12]
It still mentions the old tests spec, a link to the Fedora standard CI wiki page would be good, too, I guess. Also some other roles include a script to run the test suite, maybe it would be good here, too.

**Comment by tyll** [comment]
The script I was referring to is: https://github.com/linux-system-roles/timesync/blob/master/run-tests.sh - I guess it is outdated and would not work anymore.

**Comment by pcahyna** [comment]
Indeed, this is a relic from the pre-openshift world.

**Comment by richm** [comment]
I think this issue has been resolved - please confirm @tyll
