### ISSUE TITLE
Use standard-inventory-qcow2 from standard-test-roles

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/test-harness#13]
According to https://github.com/linux-system-roles/test-harness/blob/master/standard-inventory-qcow2#L6
standard-inventory-qcow2 should be used again from the upstream project once the patches are merged. At least the raw ping patch is merged according to https://pagure.io/standard-test-roles/commits/master?author=lars%40karlitski.net and I do not see any open PR by @larskarlitski in https://pagure.io/standard-test-roles/pull-requests

@larskarlitski can you maybe confirm that we can use the upstream version again or submit the patch as a PR?

**Comment by larskarlitski** [comment]
Yeah, both have been fixed. The other patch was done by someone else in response to me filing [issue 52](https://pagure.io/standard-test-roles/issue/52).

Thanks for noticing this!

**Comment by larskarlitski** [comment]
It's pull request #16. GitHub doesn't seem to link to it directly, only to the commit.
