### ISSUE TITLE
RFE: Use python black for code formatting

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/test-harness#32]
It would be great to have a common code style to get rid of lint warnings. The python black autoformatter looks nice:

https://github.com/ambv/black

How about using it to reformat the test harness and add a CI compliance check?

@larskarlitski @pcahyna

**Comment by larskarlitski** [comment]
Sure! I don't mind which one as long as the result is [PEP 8](https://www.python.org/dev/peps/pep-0008/?) compliant.

**Comment by tyll** [comment]
AFAICS it is PEP 8 compliant, it defaults to 88 character line length which is within the parameters. I would also not mind to use 79 characters. Just wondering, do you have a preference for another formatter?

#33 is my suggestion that also includes checks with flake8 and pycodestyle.

**Comment by pcahyna** [comment]
I am not familiar with those tools, so what is the difference between flake8, black and pycodestyle?

**Comment by tyll** [comment]
black is a tool that can change a file to a standard format that matches PEP8 conventions and some other ones. flake8 and pycodestyle are tools to check the file. pycodestyle is the successor of pep8 and checks the formatting, pyflakes checks for logical errors. Actually flake8 includes both pycodestyle and pyflakes, therefore I will change it to just run flake8. flake8 also supports another check mccabe, which checks for code complexity, which I did not activate for now, because the code would fail. Another tool that is still missing is pylint, which also checks for bad programming practices.

**Comment by pcahyna** [comment]
But in this PR, in tox.ini, black is used only to check the format, not to change the files, right?

**Comment by tyll** [comment]
Yes, it checks whether the file is formatted like the black formatter would do. This would need to be done by the author. It shows what needs to be done, though.

**Comment by pcahyna** [comment]
My question has been then how different is the check from the one performed by flake8.

**Comment by tyll** [comment]
flake8 also includes pyflakes, which checks for logical errors. I guess that if black suceeds, pycodestyle should probably not find a problem. There might be some edge cases that black does not yet handle or change but pycodestyle checks. black allows less ambiguity, for example it defaults to use double quotes unless single quotes are necesssary and pycodestyle does not care about quotes. Also black adds trailing commas. The idea to use black is not to have to care about the format too much since the black tool can also be used to do the formatting.

**Comment by pcahyna** [comment]
Thanks for the explanation.
