### ISSUE TITLE
Create one status per test suite (tests_*.yml file)

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/test-harness#38]
When a status shows failure for multiple hosts, it would be great to see which tests_*.yml file failed directly to identify the problem. Therefore it would be great to create an individual status for each tets_*.yml file - this would also create smaller ansible.log files that only belong to the individual tests and properly align better with the Standard CI interface that recommends an empty artifacts dir for each tests file. What do you think @pcahyna @larskarlitski? Should be rather easy to implement. Another advantage is that it would allow to run the tests files in parallel on multiple machines.

**Comment by larskarlitski** [comment]
Good idea! I think that would make it much easier to sift through test logs.

**Comment by pcahyna** [comment]
I generally like it, but won't be there too many statuses if a role has many tests? The number of tests will be multiplied by the number of test images and this is also likely to increase. And imagine we would like to test with multiple ansible versions...

**Comment by tyll** [comment]
Can there be too many statuses? If they are good, github hides them and if they fail, one needs to look at them.

Another problem when I looked at the code is that this would require all the workers to always checkout the repo and look if there are still some statuses for tests missing. My idea for this would be that the first worker for an image would create pending statuses for all tests that need to be done without claiming them. So then the other workers can just claim pending statuses.

**Comment by pcahyna** [comment]
> Can there be too many statuses? If they are good, github hides them and if they fail, one needs to look at them.

Probably you are right. I think I just am not able to visualize it well before I see it.

**Comment by pcahyna** [comment]
@tyll shall we abandon this?

**Comment by tyll** [comment]
> @tyll shall we abandon this?

Yes, we can close it. This specific solution might not be the best and I guess the need to run tests in parallel and to better report the logs/errors will come up again or are already mentioned in other issues.
